version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    ports:
     - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chocolate
      - POSTGRES_PASSWORD=chocisgood
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres_data: